apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wsc-pipeline.fullname" . }}-config
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ include "wsc-pipeline.kafkaBootstrap" . | quote }}
  KAFKA_TOPIC: {{ .Values.config.kafkaTopic | quote }}
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  KAFKA_GROUP_ID: {{ .Values.config.kafkaGroupId | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.config.kafkaAutoOffsetReset | quote }}
  CAREERS_URL: {{ .Values.producer.env.careersUrl | quote }}
  SCRAPE_TIMEOUT_SECONDS: {{ .Values.producer.env.scrapeTimeoutSeconds | quote }}
  SCRAPE_RETRIES: {{ .Values.producer.env.scrapeRetries | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  S3_ENDPOINT_URL: {{ include "wsc-pipeline.minioEndpoint" . | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
