apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  ports:
    - port: 9000
      name: api
    - port: 9001
      name: console
  selector:
    app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "wsc-pipeline.fullname" . }}-secret
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wsc-pipeline.fullname" . }}-secret
                  key: AWS_SECRET_ACCESS_KEY
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
