apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wsc-pipeline.fullname" . }}-secret
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
