apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper
  labels:
    {{- include "wsc-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wsc-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 5
